# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0003_auto_20171204_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='web3addr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
