# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0004_auto_20171205_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=16)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediacoin.Referral')),
            ],
        ),
    ]
