# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0005_giftcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
