# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0006_giftprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
