# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0007_auto_20171205_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
