# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0011_auto_20171206_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
