# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0012_auto_20171206_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('gift_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediacoin.GiftCode')),
            ],
        ),
    ]
