# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0013_giftrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
