# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0014_referral_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
