# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacoin', '0016_referral_referral_link_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='mediacoin.Referral')),
                ('tracked_referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_referral', to='mediacoin.Referral')),
            ],
        ),
    ]
